Add option to set any and many request headers
riramar/hsecscan pull request #14
Opened 2018-10-29 14:26 UTC by marcosvidolin

Now you can pass custom headers to the request.

2018-10-29 17:02 UTC, riramar commented
opa, valeu Marcos! Assim que tiver um tempo analiso e aprovo se for o caso.

2018-10-29 23:10 UTC, marcosvidolin commented
Legal Ricardo.
Obrigado

On Mon, Oct 29, 2018 at 2:06 PM Ricardo Iramar dos Santos <
notifications@github.com> wrote:

> opa, valeu Marcos! Assim que tiver um tempo analiso e aprovo se for o caso.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/riramar/hsecscan/pull/14#issuecomment-433992449>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABkovij0K_KBz1Abp0OjPWYmSL0ceI8nks5upzWQgaJpZM4X_Suf>
> .
>

2022-12-24 15:42 UTC, riramar requested changes
Putz. Me esqueci desse PR totalmente e isso faz só 4 anos mas gostaria de aprovar com uma modificação.
Teria como vc remover o arquivo hsecscan.pyc do PR e mandar novamente?

2022-12-24 16:08 UTC, marcosvidolin commented
Sem problemas parceiro. Eu tive que criar um novo PR porque ja nao tinha mais a branch.
Esse é o novo PR com as mesmas alterações: https://github.com/riramar/hsecscan/pull/20

2022-12-24 20:19 UTC, riramar commented
Aprovei no outro. Obrigado!

2022-12-24 20:19 UTC, closed without merging